# Generated by Django 5.0.3 on 2024-05-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
