# Generated by Django 5.0.3 on 2024-05-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_paid_order_payment_id_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
