# Generated by Django 5.0.3 on 2024-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_order_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('99.000 TO 129.000', '99.000 TO 129.000'), ('130.000 TO 200.000', '130.000 TO 200.000')], max_length=60),
        ),
    ]
